//Used for modifying some icons
import '../css/StackConstants.css';

export const StacksJSON = {
    Javascript: "javascript-plain colored",
    Java: "java-plain-wordmark colored",
    Go: "go-plain colored",
    Python: "python-plain colored",
    PHP: "php-plain colored",
    C: "c-plain colored",
    R: "r-original colored",
    Rust: "rust-plain colored",
    CSharp: "csharp-plain colored",
    CPlusPlus: "cplusplus-plain colored",
    Ruby: "ruby-plain colored",
    Typescript: "typescript-plain colored",
    ReactJS: "react-original colored",
    Gatsby: "gatsby-plain colored",
    Bootstrap: "bootstrap-plain colored",
    AngularJS: "angularjs-plain colored",
    VueJS: "vuejs-plain colored",
    Svelte: "svelte-plain colored",
    jQuery: "jquery-plain colored",
    NextJS: "nextjs-original-wordmark",
    NuxtJS: "nuxtjs-plain-wordmark colored",
    Tailwind: "tailwindcss-plain colored",
    Flutter: "flutter-plain colored",
    Spring: "spring-plain colored",
    dotNet: "dot-net-plain-wordmark colored",
    Laravel: "laravel-plain colored",
    NodeJS: "nodejs-plain-wordmark colored",
    NestJS: "nestjs-plain-wordmark colored",
    ExpressJS: "express-original-wordmark colored",
    RoR: "rails-plain-wordmark colored",
    Django: "django-plain colored",
    Flask: "flask-original-wordmark colored",
    Redis: "redis-plain colored",
    AWS: "amazonwebservices-plain colored",
    GoogleCloud: "googlecloud-plain colored",
    Azure: "azure-plain colored",
    Docker: "docker-plain colored",
    Jenkins: "jenkins-line colored",
    Travis: "travis-plain-wordmark colored",
    Kubernetes: "kubernetes-plain colored",
    MongoDB: "mongodb-plain-wordmark colored",
    PostgreSQL: "postgresql-plain-wordmark colored",
    MySQL: "mysql-plain-wordmark colored",
    Oracle: "oracle-original colored",
    Nginx: "nginx-original colored",
    Kafka: "apachekafka-original-wordmark colored",
    Apache: "apache-plain-wordmark colored",
    CircleCi: "circleci-plain-wordmark colored",
    Gitlab: "gitlab-plain-wordmark colored",
    GraphQL: "graphql-plain-wordmark colored",
    Matlab: "matlab-plain colored",
    OpenGL: "opengl-plain colored",
    Numpy: "numpy-original-wordmark colored",
    TensorFlow: "tensorflow-original-wordmark colored"

}
//Map has better performance than using an object since it is O(1) in searching
export const StacksCSSMap = new Map([
    ["Javascript", "javascript-plain colored"],
    ["Java", "java-plain-wordmark colored"],
    ["Go", "go-plain colored"],
    ["Python", "python-plain-wordmark colored python-modify"],
    ["PHP", "php-plain colored"],
    ["C", "c-plain colored"],
    ["R", "r-original colored"],
    ["Rust", "rust-plain colored"],
    ["CSharp", "csharp-plain colored"],
    ["CPlusPlus", "cplusplus-plain colored"],
    ["Ruby", "ruby-plain colored"],
    ["Typescript", "typescript-plain colored"],
    ["ReactJS", "react-original colored"],
    ["Gatsby", "gatsby-plain colored"],
    ["Bootstrap", "bootstrap-plain colored"],
    ["AngularJS", "angularjs-plain colored"],
    ["VueJS", "vuejs-plain colored"],
    ["Svelte", "svelte-plain colored"],
    ["jQuery", "jquery-plain colored"],
    ["NextJS", "nextjs-original-wordmark"],
    ["NuxtJS", "nuxtjs-plain-wordmark colored"],
    ["Tailwind", "tailwindcss-plain colored"],
    ["Flutter", "flutter-plain colored"],
    ["ReactNative", "react-original colored react-native"],
    ["Spring", "spring-plain colored"],
    ["dotNet", "dot-net-plain-wordmark colored"],
    ["Laravel", "laravel-plain colored"],
    ["NodeJS", "nodejs-plain-wordmark colored"],
    ["NestJS", "nestjs-plain-wordmark colored"],
    ["ExpressJS", "express-original-wordmark colored"],
    ["RoR", "rails-plain-wordmark colored"],
    ["Django", "django-plain colored"],
    ["Flask", "flask-original-wordmark colored"],
    ["Redis", "redis-plain colored"],
    ["AWS", "amazonwebservices-plain colored"],
    ["GoogleCloud", "googlecloud-plain colored"],
    ["Azure", "azure-plain colored"],
    ["Docker", "docker-plain colored"],
    ["Jenkins", "jenkins-line colored jenkins-modify"],
    ["Travis", "travis-plain-wordmark colored"],
    ["Kubernetes", "kubernetes-plain colored"],
    ["MongoDB", "mongodb-plain-wordmark colored"],
    ["PostgreSQL", "postgresql-plain-wordmark colored"],
    ["MySQL", "mysql-plain-wordmark colored"],
    ["Oracle", "oracle-original colored"],
    ["Nginx", "nginx-original colored"],
    ["Kafka", "apachekafka-original-wordmark colored"],
    ["Apache", "apache-plain-wordmark colored"],
    ["CircleCI", "circleci-plain-wordmark colored"],
    ["Gitlab", "gitlab-plain-wordmark colored"],
    ["GraphQL", "graphql-plain-wordmark colored"],
    ["Matlab", "matlab-plain colored"],
    ["OpenGL", "opengl-plain colored"],
    ["Numpy", "numpy-original-wordmark colored"],
    ["TensorFlow", "tensorflow-original-wordmark colored"]
]);


export const backendStacksMap = [
    {value:"Spring", label: "Spring"},
    {value:"dotNet", label: ".NET"},
    {value:"Laravel", label: "Laravel"},
    {value:"NodeJS", label: "Node.js"},
    {value:"NestJS", label: "Nest.js"},
    {value:"ExpressJS", label: "Express.js"},
    {value:"RoR", label: "Ruby on Rails"},
    {value:"Django", label: "Django"},
    {value:"Flask", label: "Flask"},
    {value:"Redis", label: "Redis"},
    {value:"AWS", label: "Amazon Web Services"},
    {value:"GoogleCloud", label: "Google Cloud Platform"},
    {value:"Azure", label: "Microsoft Azure"},
    {value:"Docker", label: "Docker"},
    {value:"Jenkins", label: "Jenkins"},
    {value:"Travis", label: "Travis"},
    {value:"Kubernetes", label: "Kubernetes"},
    {value:"MongoDB", label: "MongoDB"},
    {value:"PostgreSQL", label: "PostgreSQL"},
    {value:"MySQL", label: "MySQL"},
    {value:"Oracle", label: "Oracle"},
    {value:"Nginx", label: "Nginx"},
    {value:"Kafka", label: "Kafka"},
    {value:"Apache", label: "Apache"},
    {value:"CircleCI", label: "CircleCI"},
    {value:"Gitlab", label: "Gitlab"},
    {value:"GraphQL", label: "GraphQL"},
    {value:"Matlab", label: "Matlab"},
    {value:"OpenGL", label: "OpenGL"},
    {value:"Numpy", label: "Numpy"},
    {value:"TensorFlow", label: "TensorFlow"},
]
export const progLangsStacksMap = [
    {value:"Javascript", label: "Javascript"},
    {value:"Java", label: "Java"},
    {value:"Go", label: "Go"},
    {value:"Python", label: "Python"},
    {value:"PHP", label: "PHP"},
    {value:"C", label: "C"},
    {value:"R", label: "R"},
    {value:"Rust", label: "Rust"},
    {value:"CSharp", label: "C#"},
    {value:"CPlusPlus", label: "C++"},
    {value:"Ruby", label: "Ruby"},
    {value:"Typescript", label: "Typescript"}
]
export const frontendStacksMap = [
    {value:"ReactJS", label: "React.js"},
    {value:"Gatsby", label: "Gatsby"},
    {value:"Bootstrap", label: "Bootstrap"},
    {value:"AngularJS", label: "Angular.js"},
    {value:"VueJS", label: "Vue.js"},
    {value:"Svelte", label: "Svelte"},
    {value:"jQuery", label: "jQuery"},
    {value:"NextJS", label: "Next.js"},
    {value:"NuxtJS", label: "Nuxt.js"},
    {value:"Tailwind", label: "Tailwind"},
    {value:"Flutter", label: "Flutter"},
    {value:"ReactNative", label: "React Native"}
]